pep_version: 2.0.0
sample_table: "sample_table_srna.csv"

sample_modifiers:
  append:
    file_path_R1: "source1"
    file_path_R2: "source2"

  derive:
    attributes: [file_path_R1, file_path_R2]
    sources:
      source1: "srna_rawdata/{fq_sample_name}_R1_001.fastq.gz"
      source2: "srna_rawdata/{fq_sample_name}_R2_001.fastq.gz"
