software-deployment-method: 
  - conda
  - apptainer
singularity-args: '--nv --bind'
#e.g. '--nv --bind /users/mkelsey/data,/oscar/data/jsedivy/mkelsey /users/mkelsey/data/REVIEWER_TESEQ_TEST/genome_files /users/mkelsey/data/REVIEWER_TESEQ_TEST/genome_files /users/mkelsey/data/REVIEWER_TESEQ_TEST/genome_files  /users/mkelsey/data,/users/jsedivy/data/mkelsey,/oscar/data/jsedivy/mkelsey,/oscar/home/jkreilin/data/vesicle_RNAseq,/users/jsedivy/data/rkalekar/Github_2024/RTE/srna'

rerun-triggers: mtime
keep-going: True
rerun-incomplete: True
latency-wait: 30
executor: slurm
jobs: 30
retries: 2

default-resources:
  mem_mb: attempt * 12500
  disk_mb: 200000
  slurm_account: default
  slurm_partition: batch
  threads: 1
  runtime: attempt * 70
set-resources:
    srna_telescope:
        mem_mb: attempt * 35000
        runtime: attempt * 140
    srna_repeatanalysis_plots:
        mem_mb: attempt * 125000
        runtime: attempt * 400
    srna_enrichment_analysis_repeats:
        mem_mb: attempt * 35000
    srna_enrichment_analysis:
        mem_mb: attempt * 35000
    srna_deseq:
        mem_mb: attempt * 60000
    srna_bigwigplots:
        mem_mb: attempt * 125000
    srna_common_sortIndexBam:
        mem_mb: attempt * 35000
    srna_alignSTAR_PE:
        mem_mb: attempt * 35000
    srna_alignSTAR_SE:
        mem_mb: attempt * 35000
    aref_tldr_aggregate_multiple_samples:
        mem_mb: attempt * 125000
        runtime: attempt * 200
    aref_process_gtf_tldr:
        mem_mb: attempt * 35000
    aref_process_gtf:
        mem_mb: attempt * 35000
    aref_element_analysis:
        mem_mb: attempt * 50000
    aref_merge_genes_and_repeats_gtf:
        mem_mb: attempt * 120000
        runtime: attempt * 300
    aref_merge_genes_and_repeats_gff:
        mem_mb: attempt * 120000
        runtime: attempt * 300
    aref_makeTxDB:
        mem_mb: attempt * 60000
    aref_make_star_index:
        mem_mb: attempt * 60000
    aref_gff_to_gtf:
        mem_mb: attempt * 85000
        runtime: attempt * 200
    aref_gff_to_bed12:
        mem_mb: attempt * 85000
        runtime: attempt * 200
    aref_getRTEbeds:
        mem_mb: attempt * 35000
    aref_complete_gff3:
        mem_mb: attempt * 85000
    aref_annotate_rtes:
        mem_mb: attempt * 35000
    aref_dorado:
        cpus_per_task: 12
        slurm_partition: "gpu-he"
        mem_mb: 128000
        runtime: 5760
        slurm_extra: "'--gres=gpu:2'"
